name: AI PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    if: |
      github.event.pull_request.draft == false &&
      !startsWith(github.event.pull_request.head.ref, 'fix/ai-') &&
      !startsWith(github.event.pull_request.head.ref, 'feature/ai-task-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Review
        uses: stillrivercode/stillriver-ai-workflows@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openrouter-api-key: ${{ secrets.OPENROUTER_API_KEY }}
          ai-model: ${{ vars.AI_MODEL || 'anthropic/claude-3.5-sonnet' }}
          review-type: 'comprehensive'