name: AI PR Review

on:
  pull_request:
    types: [opened, labeled]

permissions:
  contents: read
  pull-requests: write
  issues: write
  checks: read
  actions: read

concurrency:
  group: ai-workflows-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  review:
    if: >
      github.event_name == 'pull_request' &&
      (github.event.action == 'opened' ||
       (github.event.action == 'labeled' && github.event.label.name == 'ai-review-needed')) &&
      github.event.pull_request.draft == false &&
      !startsWith(github.head_ref, 'fix/ai-') &&
      !startsWith(github.head_ref, 'feature/ai-task-')
    uses: stillrivercode/stillriver-ai-workflows/.github/workflows/ai-pr-review.yml@main
    secrets:
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}